version: "3.0"

services:
  web:
    image: nto-frontend
    container_name: frontend
    restart: unless-stopped
    # volumes:
    #   - site:/usr/share/nginx/html
    ports:
      - 20000:80
